### PR TITLE
Fix missing address bit

### PR DESCRIPTION
**Pull request by niyioyelade**
Add administrative area to town city portion of address.

### CODE REVIEW

**Comment by whpearson** [comment]
Do you know if MI uses the town_city field much? Will stats be confused with new data coming in?

**Comment by niyioyelade** [comment]
> Do you know if MI uses the town_city field much? Will stats be confused with new data coming in?

It's worth checking this, I will ask someone from the MI team

**Comment by niyioyelade** [comment]
> Do you know if MI uses the town_city field much? Will stats be confused with new data coming in?

After speaking with MI, I understand most of the MI stuff is postcode driven, so a change to the content of town_city will not make any difference. I also checked this with Andrew Hobson, he is fine with the change as well.

**Review by whpearson — APPROVED** [review]
This looks okay, it would be nicer if the faker didn't use the city data twice, so that the test could be sure of the ordering. But that shouldn't hold up the change.

**Pull request merged**
